(function(){
'use strict';
var queue=[], results=[], pollTimer=null, LSQ='dispatch_cmr_full_queue_v4';
function id(x){return document.getElementById(x)}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function toastMsg(s){if(typeof toast==='function')toast(s);else console.log(s)}
function apiAction(payload){if(typeof apiCall==='function')return apiCall('action',payload);return fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json().catch(function(){return {status:r.ok?'ok':'error'}});});}
function saveQ(){try{localStorage.setItem(LSQ,JSON.stringify(queue))}catch(e){}}
function loadQ(){try{var q=JSON.parse(localStorage.getItem(LSQ)||'[]');if(Array.isArray(q))queue=q}catch(e){queue=[]}}
function jclean(s){return String(s||'').trim().toUpperCase()}
function parseManual(txt){return String(txt||'').split(/\n\s*(?:---+)?\s*\n/g).map(function(block){return Array.from(new Set((block.match(/J[A-Z0-9]{6,}/gi)||[]).map(jclean)))}).filter(function(a){return a.length})}
function selectedKanban(){try{if(typeof g_kabSelected!=='undefined'&&g_kabSelected&&g_kabSelected.size)return Array.from(g_kabSelected)}catch(e){}return Array.from(document.querySelectorAll('.k-item.k-selected,.k-item input.k-chk:checked')).map(function(el){var card=el.closest('.k-item')||el;return card.dataset.file}).filter(Boolean)}
function addGroups(groups){groups.forEach(function(g){var files=Array.from(new Set((g||[]).map(jclean).filter(function(x){return /^J[A-Z0-9]{6,}$/.test(x)})));if(files.length)queue.push({files:files,status:'Prêt',checked:true})});saveQ();renderQueue()}
function checkedQueue(){return queue.filter(function(q){return q.checked!==false})}
function renderQueue(){var b=id('cmr4-qbody');if(!b)return;b.innerHTML=queue.length?queue.map(function(q,i){var cls=q.status==='OK'?'cmr4-ok':q.status==='KO'?'cmr4-ko':q.status==='En cours'?'cmr4-run':'';return '<tr data-q="'+i+'"><td><input type="checkbox" class="cmr4-qchk" '+(q.checked!==false?'checked':'')+'></td><td><b>BL '+(i+1)+'</b></td><td class="cmr4-file">'+esc(q.files.join(' / '))+'</td><td>'+q.files.length+'</td><td><span class="cmr4-status '+cls+'">'+esc(q.status||'Prêt')+'</span></td><td><button class="btn btn-ghost cmr4-mini" data-q-remove="'+i+'">Retirer</button></td></tr>'}).join(''):'<tr><td colspan="6" style="text-align:center;color:var(--text3);padding:22px">Queue vide.</td></tr>'}
function renderResults(){var b=id('cmr4-rbody');if(!b)return;b.innerHTML=results.length?results.map(function(r,i){var idx=(r.index!=null?r.index:i);return '<tr data-r="'+idx+'"><td><input type="checkbox" class="cmr4-rchk"></td><td><b>#'+(i+1)+'</b></td><td><div class="cmr4-file">'+esc(r.bl||'')+'</div><div class="cmr4-sub">'+esc(r.company||'')+'</div></td><td>'+esc(r.carrier||'')+'</td><td>'+esc(r.delivery||'')+'</td><td><button class="btn btn-ghost cmr4-mini" data-pdf="'+esc(r.pdf||'')+'">PDF</button> <button class="btn btn-ghost cmr4-mini" data-html="'+esc(r.html||'')+'">HTML</button> <button class="btn btn-blue-out cmr4-mini" data-edit="'+idx+'">Edit</button> <button class="btn btn-green-out cmr4-mini" data-rebuild="'+idx+'">Rebuild PDF</button> <button class="btn btn-blue-out cmr4-mini" data-mail="'+idx+'">Mail</button> <button class="btn btn-purple-out cmr4-mini" data-edoc="'+idx+'">EDOC</button></td></tr>'}).join(''):'<tr><td colspan="6" style="text-align:center;color:var(--text3);padding:22px">Aucun résultat.</td></tr>'}
function live(s){var el=id('cmr4-live');if(el)el.textContent=s}
function ensureTab(){var tabbar=id('tabbar'),content=id('content');if(!tabbar||!content)return;var tab=document.querySelector('.tab[data-tab="cmr"]');if(!tab){tab=document.createElement('div');tab.className='tab';tab.dataset.tab='cmr';tab.textContent='CMR / BL';var opt=document.querySelector('.tab[data-tab="options"]');tabbar.insertBefore(tab,opt||null)}var pane=id('tab-cmr');if(!pane){pane=document.createElement('div');pane.className='tabpane';pane.id='tab-cmr';content.appendChild(pane)}pane.innerHTML='<div class="cmr4-page"><section class="cmr4-card"><h3>CMR / BL complet</h3><div class="cmr4-sub">Colle tes J. Ligne vide ou --- = nouveau BL. Tu peux aussi envoyer la sélection Kanban.</div><textarea id="cmr4-manual" class="cmr4-text" placeholder="J1A0040247\nJ1A0040248\n\n---\nJ1A0040300"></textarea><div class="cmr4-actions"><button class="btn btn-success btn-sm" id="cmr4-add">Ajouter</button><button class="btn btn-blue-out btn-sm" id="cmr4-kanban-one">Kanban = 1 BL</button><button class="btn btn-blue-out btn-sm" id="cmr4-kanban-split">Kanban = BL séparés</button><button class="btn btn-ghost btn-sm" id="cmr4-q-all">Tout cocher</button><button class="btn btn-ghost btn-sm" id="cmr4-q-none">Tout décocher</button><button class="btn btn-danger btn-sm" id="cmr4-clear">Vider</button></div><div class="cmr4-actions" style="border-top:1px solid var(--border);padding-top:9px"><button class="btn btn-primary" id="cmr4-generate">Générer sélection</button><button class="btn btn-ghost" id="cmr4-status">Statut</button><button class="btn btn-orange-out" id="cmr4-force">Forcer output</button><button class="btn btn-danger" id="cmr4-stop">Stop queue</button></div><div class="cmr4-live" id="cmr4-live">Prêt.</div><div class="cmr4-table-wrap" style="margin-top:10px;max-height:320px"><table class="cmr4-table"><thead><tr><th></th><th>#</th><th>BL / dossiers</th><th>Nb</th><th>Statut</th><th>Action</th></tr></thead><tbody id="cmr4-qbody"></tbody></table></div></section><section class="cmr4-card"><div class="cmr4-toolbar"><div><h3>Résultats CMR</h3><div class="cmr4-sub">Actions unitaires ou groupées sur les lignes cochées.</div></div><div class="cmr4-actions"><button class="btn btn-ghost btn-sm" id="cmr4-refresh">Rafraîchir</button><button class="btn btn-blue-out btn-sm" id="cmr4-r-all">Tout cocher</button><button class="btn btn-ghost btn-sm" id="cmr4-r-none">Tout décocher</button><button class="btn btn-blue-out btn-sm" id="cmr4-mail-many">Mail sélection</button><button class="btn btn-purple-out btn-sm" id="cmr4-edoc-many">EDOC sélection</button><button class="btn btn-success btn-sm" id="cmr4-both-many">EDOC + mail</button><button class="btn btn-danger btn-sm" id="cmr4-results-clear">Clear</button></div></div><div class="cmr4-table-wrap"><table class="cmr4-table"><thead><tr><th></th><th>#</th><th>BL / société</th><th>SP</th><th>Livraison</th><th>Actions</th></tr></thead><tbody id="cmr4-rbody"></tbody></table></div></section></div>';bind();renderQueue();renderResults()}
function switchToCmr(){document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active')});document.querySelectorAll('.tabpane').forEach(function(p){p.classList.remove('active')});var t=document.querySelector('.tab[data-tab="cmr"]'),p=id('tab-cmr');if(t)t.classList.add('active');if(p)p.classList.add('active');renderQueue();renderResults()}
function selectedResultIndexes(){return Array.from(document.querySelectorAll('#cmr4-rbody tr[data-r]')).filter(function(tr){var c=tr.querySelector('.cmr4-rchk');return c&&c.checked}).map(function(tr){return tr.dataset.r})}
function setResultChecks(v){document.querySelectorAll('.cmr4-rchk').forEach(function(c){c.checked=v})}
function setQueueChecks(v){queue.forEach(function(q){q.checked=v});saveQ();renderQueue()}
function poll(){apiAction({action:'CMR_STATUS'}).then(function(r){live((r&&r.message)||JSON.stringify(r));if(r&&Array.isArray(r.results)){results=r.results;renderResults()}if(r&&r.running===false&&pollTimer){clearInterval(pollTimer);pollTimer=null}}).catch(function(e){live('Erreur statut : '+(e.message||e))})}
function startPoll(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(poll,1500);poll()}
function generate(){var qs=checkedQueue();if(!qs.length)return toastMsg('Aucun BL coché dans la queue CMR.');qs.forEach(function(q){q.status='En cours'});renderQueue();live('Génération CMR lancée...');var data=qs.map(function(q){return q.files.join(',')}).join('@@BL@@');apiAction({action:'CMR_GENERATE',data:data}).then(function(){startPoll()}).catch(function(e){live('Erreur génération : '+(e.message||e))})}
function sendMany(action,label){var idx=selectedResultIndexes();if(!idx.length)return toastMsg('Aucun résultat coché.');live(label+' : '+idx.length+' ligne(s).');apiAction({action:action,indexes:idx.join('|')}).then(function(){toastMsg(label+' lancé.');poll()}).catch(function(e){live('Erreur '+label+' : '+(e.message||e))})}
function bind(){id('cmr4-add').onclick=function(){addGroups(parseManual(id('cmr4-manual').value));id('cmr4-manual').value=''};id('cmr4-kanban-one').onclick=function(){var f=selectedKanban();if(!f.length)return toastMsg('Aucune carte Kanban sélectionnée.');addGroups([f])};id('cmr4-kanban-split').onclick=function(){var f=selectedKanban();if(!f.length)return toastMsg('Aucune carte Kanban sélectionnée.');addGroups(f.map(function(x){return [x]}))};id('cmr4-q-all').onclick=function(){setQueueChecks(true)};id('cmr4-q-none').onclick=function(){setQueueChecks(false)};id('cmr4-clear').onclick=function(){queue=[];saveQ();renderQueue()};id('cmr4-generate').onclick=generate;id('cmr4-status').onclick=poll;id('cmr4-refresh').onclick=poll;id('cmr4-force').onclick=function(){apiAction({action:'CMR_FORCE'});live('Forçage demandé.')};id('cmr4-stop').onclick=function(){apiAction({action:'CMR_STOP'});live('Stop demandé.')};id('cmr4-r-all').onclick=function(){setResultChecks(true)};id('cmr4-r-none').onclick=function(){setResultChecks(false)};id('cmr4-results-clear').onclick=function(){results=[];renderResults()};id('cmr4-mail-many').onclick=function(){sendMany('CMR_MAIL_MANY','Mails sélection')};id('cmr4-edoc-many').onclick=function(){sendMany('CMR_EDOC_MANY','EDOC sélection')};id('cmr4-both-many').onclick=function(){sendMany('CMR_EDOC_MAIL_MANY','EDOC + mail')}}
document.addEventListener('change',function(e){var q=e.target.closest('.cmr4-qchk');if(q){var tr=q.closest('tr[data-q]');if(tr){queue[Number(tr.dataset.q)].checked=q.checked;saveQ()}}});
document.addEventListener('click',function(e){var tab=e.target.closest('.tab[data-tab="cmr"]');if(tab){e.preventDefault();e.stopPropagation();ensureTab();switchToCmr();return}var rm=e.target.closest('[data-q-remove]');if(rm){queue.splice(Number(rm.dataset.qRemove),1);saveQ();renderQueue();return}var p=e.target.closest('[data-pdf]');if(p)return void apiAction({action:'CMR_OPEN_PDF',path:p.dataset.pdf});var h=e.target.closest('[data-html]');if(h)return void apiAction({action:'CMR_OPEN_HTML',path:h.dataset.html});var ed=e.target.closest('[data-edit]');if(ed)return void apiAction({action:'CMR_EDIT',index:ed.dataset.edit});var rb=e.target.closest('[data-rebuild]');if(rb)return void apiAction({action:'CMR_REBUILD_PDF',index:rb.dataset.rebuild});var m=e.target.closest('[data-mail]');if(m)return void apiAction({action:'CMR_MAIL',index:m.dataset.mail});var d=e.target.closest('[data-edoc]');if(d)return void apiAction({action:'CMR_EDOC',index:d.dataset.edoc})},true);
function init(){loadQ();ensureTab();renderQueue();renderResults()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,600)});else setTimeout(init,600);window.addEventListener('load',function(){setTimeout(init,1200)});
})();
